services:
  - type: static_site
    name: progfit-frontend
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
